name: Backend Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' # Adjust based on your project's target

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1    
    
    - name: Print file tree
      run: tree /F

    # - name: Build the SQL Project - DOTNET BUILD
    #   run: dotnet build dotnet-core-sqlproj/dotnet-core-sqlproj.sqlproj --configuration Release

    - name: Build the SQL Project - MSBUILD
      run: |
        msbuild dotnet-core-sqlproj/dotnet-core-sqlproj.sqlproj /p:Configuration=Release /p:OutputPath=./output
        echo "DACPAC file created in ./output directory"

    - name: Print file tree
      run: tree /F