name: Backend Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' # Adjust based on your project's target

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install SQL Server Data Tools
      run: |
        choco install sqlpackage -y
        echo "SQLPackage installed"
    
    - name: Print file tree
      run: tree /F

    - name: Build the SQL Project
      run: |
        msbuild dotnet-core-sqlproj.sqlproj /p:Configuration=Release /p:OutputPath=./output
        echo "DACPAC file created in ./output directory"
